### ISSUE TITLE
Doesn't hide comment?

### ISSUE THREAD

**Issue by huachuman** [MrGVSV/obsidian-better-comment-toggle#5]
For some reason it's not doing any of the hiding behavior. Just the color works. And at that, even only the text inside the comment is working. 

![GIF 1-5-2024 11-40-40 AM](https://github.com/MrGVSV/obsidian-better-comment-toggle/assets/125603964/19db1613-866e-434f-8614-147d30446e3e)

**Comment by MrGVSV** [comment]
What do you mean by "hiding behavior"? Comments in Obsidian are only hidden when in Reader Mode. If you can edit the document then the comments will still be visible. Unless I’m misunderstanding.

**Comment by huachuman** [comment]
I see, so this doesn't work in the new live editor?

**Comment by MrGVSV** [comment]
> I see, so this doesn't work in the new live editor?

No, the live editor doesn't hide comments afaik. There might be a setting for it but I’m not sure.

**Comment by MrGVSV** [comment]
Closing as I don't think this is something we'll add (unless others really want it as well). It's probably better suited for a separate comment-hiding plugin.
